
on:
  push:
    branches: [main]

jobs:
  TypeChecking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run PyRight with PyLance version
        uses: jakebailey/pyright-action@v2
        with:
            pylance-version: latest-release
